-- Q) Finding new and repeat customers (MySQL version) - Ankit Bansal

create table customer_orders (
order_id integer,
customer_id integer,
order_date date,
order_amount integer
);

INSERT INTO customer_orders (order_id, customer_id, order_date, order_amount)
VALUES 
    (1, 100, CAST('2022-01-01' AS DATE), 2000),
    (2, 200, CAST('2022-01-01' AS DATE), 2500),
    (3, 300, CAST('2022-01-01' AS DATE), 2100),
    (4, 100, CAST('2022-01-02' AS DATE), 2000),
    (5, 400, CAST('2022-01-02' AS DATE), 2200),
    (6, 500, CAST('2022-01-02' AS DATE), 2700),
    (7, 100, CAST('2022-01-03' AS DATE), 3000),
    (8, 400, CAST('2022-01-03' AS DATE), 1000),
    (9, 600, CAST('2022-01-03' AS DATE), 3000);

SELECT * FROM customer_orders;

-- Query
WITH first_order_date AS 
(
    SELECT customer_id, 
           MIN(order_date) AS first_order_date_flag
    FROM customer_orders
    GROUP BY customer_id
),
new_customer_flag AS
(
    SELECT co.*, 
           fod.first_order_date_flag,
           CASE WHEN co.order_date = fod.first_order_date_flag THEN 1 ELSE 0 END AS new_cus_flag,
           CASE WHEN co.order_date != fod.first_order_date_flag THEN 1 ELSE 0 END AS repeat_cus_flag
    FROM customer_orders AS co
    JOIN first_order_date AS fod
    ON co.customer_id = fod.customer_id
)
SELECT order_date,
       SUM(new_cus_flag) AS new_customers,
       SUM(repeat_cus_flag) AS repeated_customers
FROM new_customer_flag
GROUP BY order_date;

-- Q. 1a) Finding out amount generated by new and repeat customers each day

WITH first_order_date As 
(
select 
    customer_id, 
    min(order_date) as first_order_date_flag
from customer_orders
group by customer_id
),
amount_order_flag as (
select 
    co.order_date,
    SUM(CASE WHEN co.order_date = fod.first_order_date_flag THEN co.order_amount ELSE 0 END ) AS new_flag,
    SUM(CASE WHEN co.order_date != fod.first_order_date_flag THEN co.order_amount ELSE 0 END ) AS repeat_flag
from customer_orders As co
INNER JOIN first_order_date As fod
ON co.customer_id = fod.customer_id
GROUP BY co.order_date
ORDER BY co.order_date
)
select * 
from amount_order_flag


